import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import { Footer, Header, Sidebar } from './components';

import styles from './layout.module.scss';

import './globals.scss';

const notoSans = Noto_Sans({
  weight: ['300', '400', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.className}>
      <body>
        <div className={styles.layout}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <main className={styles.main}>{children}</main>
          <Footer className={styles.footer} />
        </div>
      </body>
    </html>
  );
}
