import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import { MainLayout, ScrollToTopButton } from '@/components';

import './globals.scss';

const notoSans = Noto_Sans({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'LearnCatalog - Explore and master new skills with curated courses',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.className}>
      <body>
        <MainLayout>{children}</MainLayout>
        <ScrollToTopButton />
      </body>
    </html>
  );
}
