import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

import './globals.scss';

const notoSans = Noto_Sans({
  weight: ['300', '400', '600', '700'],
  subsets: ['cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>{children}</body>
    </html>
  );
}
